In [1]:
import numpy as np

In [2]:
v = np.linspace(0,10,5)

In [3]:
v[0]

0.0

In [4]:
v[1]

2.5

In [5]:
v[-1]

10.0

In [6]:
vv = np.random.random((5,4))

In [7]:
vv

array([[0.62931564, 0.17822181, 0.07672731, 0.28738887],
       [0.16460918, 0.66232812, 0.96853358, 0.27120489],
       [0.95774409, 0.48027478, 0.29208248, 0.77866129],
       [0.299324  , 0.18130457, 0.14742974, 0.48170311],
       [0.53197118, 0.08802276, 0.63944489, 0.38175086]])

In [8]:
'List of lists'
ll = [[1,2,3,4],[5,6,7,8]]

In [9]:
ll

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
'Slicing values from arrays'
v[2:4]

array([5. , 7.5])

In [11]:
'Counting from the end'
vv[2:-1]

array([[0.95774409, 0.48027478, 0.29208248, 0.77866129],
       [0.299324  , 0.18130457, 0.14742974, 0.48170311]])

In [12]:
'Step in thrue every 2 otems in the array'
vv[:,::2]

array([[0.62931564, 0.07672731],
       [0.16460918, 0.96853358],
       [0.95774409, 0.29208248],
       [0.299324  , 0.14742974],
       [0.53197118, 0.63944489]])

In [13]:
'Important - '
'Numpy slices ill vies to the same pice of memory, in case we assign arry to new array and edit the original arraty'
v2 = v[2:4]

In [14]:
v2[0] = 0

In [15]:
'The values has been changes in the original array'
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [16]:
'If we dont want the changes will afect on the original array, we need to use a copy'
v3 = v[2:4].copy()

In [17]:
v3[0] = 1

In [18]:
v3

array([1. , 7.5])

In [19]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [20]:
'Advance indexing:'
'Use a lists of indexes to select a surtant elemant'
v[[1,2,3]]

array([2.5, 0. , 7.5])

In [21]:
'True of false operarions'
'Choose elemants that grater the zerow'
v > 0

array([False,  True, False,  True,  True])

In [22]:
'Assign the results of this comperison to another array '
bool_index = v > 0

In [23]:
'Use this array to index the original array'
v[bool_index]

array([ 2.5,  7.5, 10. ])

In [24]:
'We can allso use tihs indexing to cerfuly modifing only part of the values in the array'
'Make sure that the both sides of the operator need to bwe compatibal'
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [25]:
vv

array([[1.25863128, 0.17822181, 0.07672731, 0.28738887],
       [0.16460918, 1.32465624, 1.93706716, 0.27120489],
       [1.91548817, 0.48027478, 0.29208248, 1.55732259],
       [0.299324  , 0.18130457, 0.14742974, 0.48170311],
       [1.06394236, 0.08802276, 1.27888978, 0.38175086]])

In [26]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [27]:
vv[0,1]

0.17822181277949833

In [28]:
vv

array([[1.25863128, 0.17822181, 0.07672731, 0.28738887],
       [0.16460918, 1.32465624, 1.93706716, 0.27120489],
       [1.91548817, 0.48027478, 0.29208248, 1.55732259],
       [0.299324  , 0.18130457, 0.14742974, 0.48170311],
       [1.06394236, 0.08802276, 1.27888978, 0.38175086]])