In [2]:
import numpy as np
import matplotlib.pyplot as pp


In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a.dtype

dtype('int32')

In [6]:
a = np.array([1,2,3,5], dtype=np.float64)

In [7]:
a

array([1., 2., 3., 5.])

In [8]:
'Number of dimentions in arry'
a.ndim

1

In [9]:
'The shape of the arry arry'
a.shape

(4,)

In [10]:
'The total size of arry arry'
a.size

4

In [14]:
b = np.array([[1,2,3,5],[6,7,8,9]],dtype=np.float64)

In [16]:
b

array([[1., 2., 3., 5.],
       [6., 7., 8., 9.]])

In [17]:
b.ndim, b.shape, b.size

(2, (2, 4), 8)

In [20]:
np.zeros((3,3), 'd')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.empty((4,4), 'd')

array([[4.67296746e-307, 1.69121096e-306, 2.20675244e-280,
        1.17223259e-280],
       [8.34441751e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [22]:
'Arry with 5  ellements between 0 and 10'
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
'Arry with x ellements by range between 0 and 10'
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [25]:
'Arry with random numbers'
np.random.standard_normal((2,4))

array([[ 1.55829954, -1.183296  , -0.24267401, -1.25466029],
       [-0.01946397,  0.7144169 ,  0.14476218, -1.4681605 ]])

In [27]:
'Combine (stack)  2 arrys with the same dimentions'
'Gives us arry with 4 rows and 3 columns'
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[-1.06739573,  0.41741073,  0.02776438],
       [-0.40625636,  1.92034881, -0.67421137],
       [-0.27253098, -0.9025595 , -0.16287491],
       [ 0.60367931, -0.83191225,  1.12158421]])

In [28]:
'Combine HORIZONTAL (stack) 2 arrys with the same dimentions'
'Gives us arry with 2 rows and 6 columns'

np.hstack([a,b])

array([[-1.06739573,  0.41741073,  0.02776438, -0.27253098, -0.9025595 ,
        -0.16287491],
       [-0.40625636,  1.92034881, -0.67421137,  0.60367931, -0.83191225,
         1.12158421]])

In [30]:
'Take the TRANSPOSE of an arry'
'Rows become columns and vice versa'

a.transpose()

array([[-1.06739573, -0.40625636],
       [ 0.41741073,  1.92034881],
       [ 0.02776438, -0.67421137]])

In [31]:
'Save arry to file'
np.save('Example.npy',a)

In [32]:
'Load arry from file'
a1 = np.load('Example.npy')

In [33]:
a1

array([[-1.06739573,  0.41741073,  0.02776438],
       [-0.40625636,  1.92034881, -0.67421137]])